name: grphChat
version: ${project.version}
main: com.grphcrtv.GrphChat
commands:
  namecolour:
    description: Change name colour for chat messages
    uage: "Usage: '/namecolour [colour]' to set your name colour!"